# Generated by Django 3.2.5 on 2022-04-13 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
