# Generated by Django 3.2.5 on 2021-12-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_blog', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
