# Generated by Django 3.2.5 on 2022-04-13 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_blog', '0011_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='test_blog.comment'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
