# Generated by Django 3.2.5 on 2022-04-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_blog', '0013_auto_20220413_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='timestamp',
            new_name='created_date',
        ),
    ]
