# Generated by Django 3.2.5 on 2022-04-13 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_blog', '0014_rename_timestamp_reply_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
