# Generated by Django 3.2.5 on 2022-04-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_blog', '0015_auto_20220413_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply',
            new_name='text',
        ),
    ]
