# Generated by Django 3.2.5 on 2022-04-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_blog', '0016_rename_reply_reply_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_date']},
        ),
    ]
